spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dewdrop?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect